module.exports = {
    ALBUM_META_JSON: 'album-meta.json',
    APP_DIRECTORY: './app/pages',
    DEFAULT_IMAGE_DIRECTORY: '__original',
    DEMO_ALBUM: 'demo-album',
    DEMO_PIX: [
        'kaboom_1_demo.jpg',
        'kaboom_2_demo.jpg',
        'kaboom_3_demo.jpg',
        'kaboom_4_demo.jpg'
    ],
    DUMMY_RESOURCE_PATH: './src/build-scripts/dummy',
    GALLERY_ACTIVE_PATH: './gallery-active',
    GALLERY_STATIC_PATH: './gallery-static',
    SITE_NAV_JSON: 'site-nav.json',
    SVGO_PARAMS: {
        multipass: true,
        plugins: [{ cleanupAttrs: true }, 
            { removeDoctype: true },
            { removeXMLProcInst: true },
            { removeComments: true },
            { removeMetadata: true },
            { removeTitle: true },
            { removeDesc: true },
            { removeUselessDefs: true },
            { removeEditorsNSData: true },
            { removeEmptyAttrs: true },
            { removeHiddenElems: true },
            { removeEmptyText: true },
            { removeEmptyContainers: true },
            { removeViewBox: false },
            { cleanupEnableBackground: true },
            { convertStyleToAttrs: true },
            { convertColors: true },
            { convertPathData: { floatPrecision: 1} },
            { convertTransform: true },
            { removeUnknownsAndDefaults: true },
            { removeNonInheritableGroupAttrs: true },
            { removeUselessStrokeAndFill: true },
            { removeUnusedNS: true },
            { cleanupIDs: true },
            { cleanupNumericValues: { floatPrecision: 1} },
            { moveElemsAttrsToGroup: true },
            { moveGroupAttrsToElems: true },
            { collapseGroups: true },
            { removeRasterImages: false },
            { mergePaths: true },
            { convertShapeToPath: true },
            { sortAttrs: true },
            { removeDimensions: true },
            { removeAttrs: {attrs: '(stroke|fill)'} },
            { reusePaths: true }
        ]
    }
};
